version: "3.7"

services:
  # lms:
  #   image: lms-php
  #   volumes:
  #     - ./:/lms
  #   working_dir: /lms
  php:
    build:
      context: ./php
    restart: always
    volumes:
        # - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        - "./lms:/var/www/html"
    ports:
      - 9000:9000
    networks:
      services-network:
        aliases:
          - nginx
    links:
      - mysql:mysql
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./webservice/nginx:/etc/nginx/conf.d
      - ./webservice/certbot/conf:/etc/letsencrypt
      - ./webservice/certbot/www:/var/www/certbot
      - ./lms:/var/www/html
    # command: "cp -rf /data/lms /var/www/lms"
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - php
      - mysql
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./webservice/certbot/conf:/etc/letsencrypt
      - ./webservice/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  mysql:
    image: mysql:5.7.21
    volumes:
      - ./:/lms
      - dbdata:/var/lib/mysql
    environment:
      # - MYSQL_DATABASE=world
      - MYSQL_ROOT_PASSWORD=root
    working_dir: /lms
    depends_on: 
      - php
    networks:
      services-network:
        aliases:
          - mysql

volumes:
  dbdata:

networks:
  services-network:
    name: services-network
    driver: bridge