version: "3.7"

services:
  php:
    image: vultr-php
    build:
      context: ./php
    volumes:
      - ./:/lms
    working_dir: /lms
  web:
    image: vultr-nginx
    build:
      context: ./nginx
    volumes:
      - ./:/lms
    depends_on:
      - php
    ports:
      - 80:80
  mysql:
    image: mysql:5.7.21
    volumes:
      - ./:/lms
      - dbdata:/var/lib/mysql
    environment:
      # - MYSQL_DATABASE=world
      - MYSQL_ROOT_PASSWORD=root123$
    working_dir: /lms

volumes:
  dbdata:
