version: "3.7"

services:
  php:
    image: lms-php
    build:
      context: ./php
    volumes:
      - ./:/lms
    working_dir: /lms

  nginx-letsencrypt:
    image: linuxserver/letsencrypt
    container_name: lms-nginx-letsencrypt
    volumes:
      - ./nginx/letsencrypt:/config
      - ./nginx/default.conf /etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    environment:
      - EMAIL=ninjadev999@gmail.com
      - URL=vultrwin.com
      - SUBDOMAINS=www
      - VALIDATION=http
      - TZ=UTC
      - PUID=0
      - PGID=0

  mysql:
    image: mysql:5.7.21
    volumes:
      - ./:/lms
      - dbdata:/var/lib/mysql
    environment:
      # - MYSQL_DATABASE=world
      - MYSQL_ROOT_PASSWORD=root
    working_dir: /lms

volumes:
  dbdata:
